
seed: 42

observation:
  scale: 1.0
  focal_mm: 50

intboard:
  board_name: calibboard
  observation: F15_av16
  board_size_mm: 40

psfboard:
  board_name: psfboard3
  observation: F15
  board_size_mm: 40
  target_focal: 2.8
  focal_distance_mm: 1500
  patch_size_area: 0.75
  patch_size_mul: 32
  diffusion_epoch: 50
  use_diffusion_denoising: true
  batchsize: 8

blobParams:
  minthres: 0.1
  maxthres: 0.95
  filterByArea: false
  filterByCircularity: true
  minCircularity: 0.1
  filterByConvexity: true
  minConvexity: 0.87
  filterByInertia: true
  minInertiaRatio: 0.01