
_target_: src.model.model.PSFVolumeModule

model_cfg:
  patchRatio: 0.46   # this is crucial for learning the PSF, make sure this is big enough
  bound_margin: 0.1
  gradient_method: 'sobel'
  w_diffusion: false
  normalize_input: true
  use_symmetric_loss: true

  psf_volume:
    psf_feat:
      _target_: src.model.components.mixed.PSFGrid
      _partial_: true
      coarse_level: 16
      coarse_size: 64
      num_level: 8  # multi-level of the hashgrid
    psf_mlp:
      _target_: src.model.components.mlp.MLP
      _partial_: true
      in_dim: 1
      hidden_dims: [64, 64]
      out_dim: 2
      weight_norm: true
      weight_init: false
      activation: 'Softplus'
      out_activation: 'Softplus100'  # should be carefully watched, seems not working well
      scale_term: 0.001
    embedder:
      _target_: src.model.components.embedding.FourierEmbedder
      _partial_: true
      multires: 6

  loss_weight:
    recon: 1.0
    ssim: 1.0
    sym: 1.0
    tv: 0.01
    regl1: 0.01
    tv_dense: 1e-5

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  betas: [0.9, 0.999]
  eps: 1e-8

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.5
  patience: 2

# compile model for faster training with pytorch 2.0
compile: false