
_target_: src.model.model.PSFVolumeModule

model_cfg:
  level: 64  # depth level of the psf volume
  patchRatio: 0.46   # this is crucial for learning the PSF, make sure this is big enough
  gradient_method: 'sobel'
  w_diffusion: false
  normalize_input: true
  use_symmetric_loss: true

  psf_volume:
    psf_feat:
      _target_: src.model.components.hashgrid.HashPSFGrid
      _partial_: true
      in_dim: 3
      num_level: 16
    psf_mlp:
      _target_: src.model.components.mlp.TCNNMLP
      _partial_: true
      in_dim: 5
      hidden_dim: 64
      n_hidden_layers: 2
      out_dim: 6
      activation: 'None'
      scale_term: 0.001
      
  loss_weight:
    recon: 1.0
    ssim: 1.0
    regl1: 0.01
    tv: 0.01
    sym: 0.01

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  betas: [0.9, 0.999]
  eps: 1e-8

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.5
  patience: 2

# compile model for faster training with pytorch 2.0
compile: false