
_target_: src.model.model.PSFVolumeModule

model_cfg:
  level: 16  # depth level of the hashgrid
  patchRatio: 0.36  # this is crucial for learning the PSF, make sure this is big enough
  gradient_method: 'sobel'
  w_diffusion: true
  normalize_input: true
  use_symmetric_loss: true

  psf_volume:
    psf_feat:
      _target_: src.model.components.hashgrid.HashPSFGrid
      _partial_: true
      in_dim: 3
      num_level: ${model.model_cfg.level}
    psf_mlp:
      _target_: src.model.components.mlp.MLP
      _partial_: true
      in_dim: 5
      hidden_dims: [64, 64]
      out_dim: 6
      weight_norm: true
      weight_init: false
      activation: 'Softplus'
      scale_term: 0.001
    embedder:
      _target_: src.model.components.embedding.FourierEmbedder
      _partial_: true
      multires: 6

  loss_weight:
    recon: 1.0
    ssim: 1.0
    regl1: 0.01
    tv: 0.01

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  betas: [0.9, 0.999]
  eps: 1e-8

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5

# compile model for faster training with pytorch 2.0
compile: false