
_target_: src.model.model1.PSFVolumeModule

model_cfg:
  multires: true
  level: 16
  use_deblur_volume: false
  normalize_input: true
  w_diffusion: false

  psf_volume:
    patch_uvsize: 57  # this is crucial for learning the PSF, Make sure kernel is big enough.
    psf_feat:
      _target_: src.model.components.hashgrid.HashPSFGrid
      _partial_: true
      in_dim: 3
    psf_mlp:
      _target_: src.model.components.mlp.MLP
      _partial_: true
      in_dim: 5
      hidden_dims: [64, 64]
      out_dim: 6
      weight_norm: true
      weight_init: false
      activation: 'Softplus'
      scale_term: 0.001
    embedder:
      _target_: src.model.components.embedding.FourierEmbedder
      _partial_: true
      multires: 6

  loss_weight:
    recon: 1.0
    ssim: 1.0
    regl1: 0.01
    tv: 0.01

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  betas: [0.9, 0.999]
  eps: 1e-8

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5

# compile model for faster training with pytorch 2.0
compile: false