# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory (put here)
calib_data_dir: "./data/DP_data/2024_dp_calib/cam_calib/${calib.intboard.observation}"  # save observations related to intrinsic calibration
psf_data_dir: "./data/DP_data/2024_dp_calib/psf_calib/${calib.psfboard.observation}"  # save observations related to PSF calibration

# path to board directory
board_dir: ${paths.root_dir}/boards/

# path to output directory
log_dir: ${paths.root_dir}/logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}