defaults:
  - model_checkpoint
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirname: "checkpoints"
  dirpath: ${paths.output_dir}/${callbacks.model_checkpoint.dirname}
  filename: "epoch_{epoch:03d}"
  save_last: True
  auto_insert_metric_name: False

model_summary:
  max_depth: -1